const OK=200
const CREATED=201
const UNPROCESSED_ENTITY=422
const INTERNAL_SERVER_ERROR=500
const BAD_REQUEST=400
const NOT_FOUND=404
const UN_AUTHORIZED=401
const FORBIDDEN=403
const NO_CONTENT=204

module.exports = {
  OK,
  CREATED,
  UNPROCESSED_ENTITY,
  BAD_REQUEST,
  FORBIDDEN,
  NO_CONTENT,
  INTERNAL_SERVER_ERROR,
  UN_AUTHORIZED,
  NOT_FOUND,
};